# ESTO ES UN COMENTARIO
# Todo lo que está a la derecha de # es solo para nosotros

version: 0.3.5 # NO TOCAR

# Configuración Global
html:
# title: Este valor no funciona porque esta comentado
  title: Links | ceciliaolivemktg # Este es el Título que aparece en la pestaña de navegador

# Colores de plantilla
theme:
  background_color: "#DFDEE4"
  # cover_color: "#BCA7CA"

# Configuración Central
main:
  title: Cecilia Olive # Aca podes poner tu nombre o el de tu producto

# Lista de bloques
blocks:
  # Estos bloques los podes editar cambiando SOLO el texto que está en blanco
  # Sacale 

  - title: Instagram
    icon: instagram
    url: https://www.instagram.com/ceciliaolivemktg/
    
  - title: Whatsapp
    icon: whatsapp
    url: https://wa.me/message/DDBSFQMLIUG6F1

  - title: Twitter
    icon: twitter
    url: https://twitter.com/ceciliaolivemkt
    
  - title: LinkedIn # Este es el nombre del botón
    icon: linkedin # Este es el nombre del icono (si queres añadir una red social nueva, prestá atencion que es todo con minúscula)
    url: https://www.linkedin.com/in/ceciliaolive/ # Link a donde redireccionará al hacer click

  - title: Github
    icon: github
    url: https://ceciliaolivemktg.github.hodl.ar/

  - title: Sitio Web
    icon: url
    url: https://ceciliaolivemktg.com/

# - title: Telegram
#   icon: telegram
#   url: https://t.me/TU-USUARIO
    
# Guardá el archivo haciendo click en Commit Changes, abajo
# Volvé a las instrucciones
